/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yloksaiixyjypxrzpycs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb2tzYWlpeHlqeXB4cnpweWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTg5MzIsImV4cCI6MjA3MTk5NDkzMn0.o2GJ8YQKCP7n_8lhpNG-vp1W-0dDL6jOzznp7QCou8s"